/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MKL02Z16xxx4
package_id: MKL02Z16VFM4
mcu_data: ksdk2_0
processor_version: 6.0.0
pin_labels:
- {pin_num: '16', pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK, label: ADC_3V3_BUS_ISEN}
- {pin_num: '15', pin_signal: ADC0_SE7/PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI, label: ADC_BUS_3V3_ISEN}
- {pin_num: '13', pin_signal: ADC0_SE9/PTB10/TPM0_CH1, label: ADC_SOL_ISEN}
- {pin_num: '12', pin_signal: ADC0_SE10/PTB9, label: ADC_BAT_RAW_ISEN}
- {pin_num: '25', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, label: ADC_BAT_VSEN}
- {pin_num: '11', pin_signal: ADC0_SE11/PTB8, label: ADC_BATV_BUS_ISEN}
- {pin_num: '26', pin_signal: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0, label: ADC_SOL_VSEN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '16', peripheral: ADC0, signal: 'SE, 9', pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK}
  - {pin_num: '15', peripheral: ADC0, signal: 'SE, 10', pin_signal: ADC0_SE7/PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI}
  - {pin_num: '11', peripheral: ADC0, signal: 'SE, 14', pin_signal: ADC0_SE11/PTB8}
  - {pin_num: '25', peripheral: ADC0, signal: 'SE, 1', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b}
  - {pin_num: '26', peripheral: ADC0, signal: 'SE, 0', pin_signal: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0}
  - {pin_num: '13', peripheral: ADC0, signal: 'SE, 12', pin_signal: ADC0_SE9/PTB10/TPM0_CH1}
  - {pin_num: '12', peripheral: ADC0, signal: 'SE, 13', pin_signal: ADC0_SE10/PTB9}
  - {pin_num: '24', peripheral: I2C0, signal: SDA, pin_signal: PTB4/IRQ_11/I2C0_SDA/UART0_RX}
  - {pin_num: '23', peripheral: I2C0, signal: SCL, pin_signal: PTB3/IRQ_10/I2C0_SCL/UART0_TX}
  - {pin_num: '3', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD}
  - {pin_num: '4', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '5', peripheral: ADC0, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '6', peripheral: SUPPLY, signal: 'VSS, 8', pin_signal: VSS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    /* PORTA12 (pin 26) is configured as ADC0_SE0 */
    PORT_SetPinMux(PORTA, 12U, kPORT_PinDisabledOrAnalog);

    /* PORTA7 (pin 15) is configured as ADC0_SE7 */
    PORT_SetPinMux(PORTA, 7U, kPORT_PinDisabledOrAnalog);

    /* PORTB0 (pin 16) is configured as ADC0_SE6 */
    PORT_SetPinMux(PORTB, 0U, kPORT_PinDisabledOrAnalog);

    /* PORTB10 (pin 13) is configured as ADC0_SE9 */
    PORT_SetPinMux(PORTB, 10U, kPORT_PinDisabledOrAnalog);

    /* PORTB3 (pin 23) is configured as I2C0_SCL */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt2);

    /* PORTB4 (pin 24) is configured as I2C0_SDA */
    PORT_SetPinMux(PORTB, 4U, kPORT_MuxAlt2);

    /* PORTB5 (pin 25) is configured as ADC0_SE1 */
    PORT_SetPinMux(PORTB, 5U, kPORT_PinDisabledOrAnalog);

    /* PORTB8 (pin 11) is configured as ADC0_SE11 */
    PORT_SetPinMux(PORTB, 8U, kPORT_PinDisabledOrAnalog);

    /* PORTB9 (pin 12) is configured as ADC0_SE10 */
    PORT_SetPinMux(PORTB, 9U, kPORT_PinDisabledOrAnalog);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
