/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C2.c
**     Project     : EPS_Basic
**     Processor   : MKL02Z32VFM4
**     Component   : I2C_LDD
**     Version     : Component 01.016, Driver 01.07, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-18, 10:23, # CodeGen: 0
**     Abstract    :
**          This component encapsulates the internal I2C communication
**          interface. The implementation of the interface is based
**          on the Philips I2C-bus specification version 2.0.
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible
**              (see SendStop parameter in MasterSend/ReceiveBlock method)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
**     Settings    :
**          Component name                                 : I2C2
**          I2C channel                                    : I2C0
**          Interrupt service                              : Enabled
**            Interrupt                                    : INT_I2C0
**            Interrupt priority                           : high priority
**          Settings                                       : 
**            Mode selection                               : SLAVE
**            MASTER mode                                  : Disabled
**            SLAVE mode                                   : Enabled
**              Address mode                               : 7-bit addressing
**              Slave address                              : 0x2A
**              General call address                       : Disabled
**              Clock stretching                           : Disabled
**                Empty character                          : 0
**              Slave baud rate control                    : Disabled
**              Wake-up                                    : Enabled
**            Pins                                         : 
**              SDA pin                                    : 
**                SDA pin                                  : PTB4/IRQ_11/I2C0_SDA/UART0_RX
**                SDA pin signal                           : I2C_SDA
**              SCL pin                                    : 
**                SCL pin                                  : PTB3/IRQ_10/I2C0_SCL/UART0_TX
**                SCL pin signal                           : I2C_SCL
**              High drive select                          : Disabled
**              Input Glitch filter                        : 5
**            Internal frequency (multiplier factor)       : 20.97152 MHz
**            Bits 0-2 of Frequency divider register       : 010
**            Bits 3-5 of Frequency divider register       : 100
**            SCL frequency                                : 93.623 kHz
**            SDA Hold                                     : 1.574 us
**            SCL start Hold                               : 5.245 us
**            SCL stop Hold                                : 5.388 us
**          Initialization                                 : 
**            Enabled in init code                         : yes
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnMasterBlockSent                          : Disabled
**              OnMasterBlockReceived                      : Disabled
**              OnMasterByteReceived                       : Disabled
**              OnSlaveBlockSent                           : Enabled
**              OnSlaveBlockReceived                       : Enabled
**              OnSlaveByteReceived                        : Enabled
**              OnSlaveRxRequest                           : Enabled
**              OnSlaveTxRequest                           : Enabled
**              OnSlaveGeneralCallAddr                     : Disabled
**              OnError                                    : Enabled
**              OnBusStartDetected                         : Disabled
**              OnBusStopDetected                          : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init                         - LDD_TDeviceData* I2C2_Init(LDD_TUserData *UserDataPtr);
**         SlaveSendBlock               - LDD_TError I2C2_SlaveSendBlock(LDD_TDeviceData *DeviceDataPtr, LDD_TData...
**         SlaveGetBlockSentStatus      - bool I2C2_SlaveGetBlockSentStatus(LDD_TDeviceData *DeviceDataPtr);
**         SlaveGetSentDataNum          - LDD_I2C_TSize I2C2_SlaveGetSentDataNum(LDD_TDeviceData *DeviceDataPtr);
**         SlaveCancelTransmissionBlock - LDD_TError I2C2_SlaveCancelTransmissionBlock(LDD_TDeviceData *DeviceDataPtr);
**         SlaveReceiveBlock            - LDD_TError I2C2_SlaveReceiveBlock(LDD_TDeviceData *DeviceDataPtr, LDD_TData...
**         SlaveGetBlockReceivedStatus  - bool I2C2_SlaveGetBlockReceivedStatus(LDD_TDeviceData *DeviceDataPtr);
**         SlaveGetReceivedDataNum      - LDD_I2C_TSize I2C2_SlaveGetReceivedDataNum(LDD_TDeviceData *DeviceDataPtr);
**         SlaveUpdateReceiveBlockSize  - LDD_TError I2C2_SlaveUpdateReceiveBlockSize(LDD_TDeviceData *DeviceDataPtr,...
**         SlaveCancelReceptionBlock    - LDD_TError I2C2_SlaveCancelReceptionBlock(LDD_TDeviceData *DeviceDataPtr);
**         GetError                     - LDD_TError I2C2_GetError(LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TErrorMask...
**         CheckBus                     - LDD_TError I2C2_CheckBus(LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TBusState...
**         GetStats                     - LDD_I2C_TStats I2C2_GetStats(LDD_TDeviceData *DeviceDataPtr);
**         ClearStats                   - void I2C2_ClearStats(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C2.c
** @version 01.07
** @brief
**          This component encapsulates the internal I2C communication
**          interface. The implementation of the interface is based
**          on the Philips I2C-bus specification version 2.0.
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible
**              (see SendStop parameter in MasterSend/ReceiveBlock method)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
*/         
/*!
**  @addtogroup I2C2_module I2C2 module documentation
**  @{
*/         

/* MODULE I2C2. */

#include "Events.h"
#include "I2C2.h"
#include "PORT_PDD.h"
#include "I2C_PDD.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* SerFlag bits */
#define MASTER_IN_PROGRES       0x01U  /* Communication is in progress (Master) */

/* StatusFlag bits */
#define SLAVE_BLOCK_SENT        0x04U  /* Slave data block sent flag */
#define SLAVE_BLOCK_RECEIVED    0x08U  /* Slave data block received flag */

typedef struct {
  uint8_t SerFlag;                     /* Flags for serial communication */
                                       /* Bits: 0 - Running int from TX */
  uint8_t StatusFlag;                  /* Flags for status of communication */
  LDD_I2C_TErrorMask ErrorMask;        /* Variable for errors mask value */
  LDD_I2C_TSize InpLenS;               /* The counter of input bufer's content */
  LDD_I2C_TSize InpLenSReq;            /* Length of input bufer's content */
  uint8_t *InpPtrS;                    /* Pointer to input buffer for Slave mode */
  LDD_I2C_TSize OutLenS;               /* The counter of output bufer's content */
  LDD_I2C_TSize OutLenSReq;            /* Length of output bufer's content */
  uint8_t *OutPtrS;                    /* Pointer to output buffer for Slave mode */
  LDD_TUserData *UserData;             /* RTOS device data structure */
  LDD_I2C_TStats Stats;                /* Communication statistics */
} I2C2_TDeviceData;

typedef I2C2_TDeviceData *I2C2_TDeviceDataPtr; /* Pointer to the device data structure. */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static I2C2_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static I2C2_TDeviceDataPtr INT_I2C0__DEFAULT_RTOS_ISRPARAM;

#define AVAILABLE_EVENTS_MASK (LDD_I2C_ON_SLAVE_BLOCK_SENT | LDD_I2C_ON_SLAVE_BLOCK_RECEIVED | LDD_I2C_ON_SLAVE_TX_REQUEST | LDD_I2C_ON_SLAVE_RX_REQUEST | LDD_I2C_ON_ERROR | LDD_I2C_ON_SLAVE_BYTE_RECEIVED)

/*
** ===================================================================
**     Method      :  I2C2_Interrupt (component I2C_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_SLAVE_BLOCK_SENT     0x01U
#define ON_SLAVE_BLOCK_RECEIVED 0x02U

PE_ISR(I2C2_Interrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  I2C2_TDeviceDataPtr DeviceDataPrv = INT_I2C0__DEFAULT_RTOS_ISRPARAM;
  uint8_t Flags = 0x00U;               /* Temporary variable for flags */
  LDD_I2C_TErrorMask ErrorMask = 0x00U; /* Temporary variable for error mask */
  register uint8_t Status;             /* Temporary variable for status register */

  Status = I2C_PDD_ReadStatusReg(I2C0_BASE_PTR); /* Safe status register */
  I2C_PDD_ClearInterruptFlags(I2C0_BASE_PTR, (Status)); /* Clear interrupt flag */
  if (I2C_PDD_GetMasterMode(I2C0_BASE_PTR) == I2C_PDD_MASTER_MODE) { /* Is device in master mode? */
  } else {
    if ((Status & I2C_PDD_ADDRESSED_AS_SLAVE) != 0x00U) { /* Addressed as a slave? */
      if ((Status & I2C_PDD_ARBIT_LOST) != 0x00U) { /* Arbitration lost? */
        ErrorMask |= LDD_I2C_ARBIT_LOST; /* Set the ArbitLost error mask */
        DeviceDataPrv->Stats.ArbitLost++; /* Increment ArbitLost counter */
      }
      if ((Status & I2C_PDD_SLAVE_TRANSMIT) != 0x00U) { /* Read? */
        I2C2_OnSlaveTxRequest(DeviceDataPrv->UserData); /* Invoke OnSlaveTxRequest event */
        I2C_PDD_SetTransmitMode(I2C0_BASE_PTR, I2C_PDD_TX_DIRECTION); /* Switch to Tx mode */
        if (DeviceDataPrv->OutLenS < DeviceDataPrv->OutLenSReq) { /* Is the requested number of characters transmitted? */
          DeviceDataPrv->OutLenS++;    /* Increment number of chars in the transmit buffer */
          I2C_PDD_WriteDataReg(I2C0_BASE_PTR, *(DeviceDataPrv->OutPtrS)++); /* Store char to transmitter register */
          DeviceDataPrv->Stats.SlaveSentChars++; /* Increment SlaveSentChars counter */
          if (DeviceDataPrv->OutLenS == DeviceDataPrv->OutLenSReq) { /* Is last char. transmitted? */
            Flags |= ON_SLAVE_BLOCK_SENT; /* Set OnSlaveBlockSent flag if last character was sent */
            DeviceDataPrv->OutLenSReq = 0x00U; /* Slave block is transmitted */
          }
        } else {
          I2C_PDD_WriteDataReg(I2C0_BASE_PTR, I2C2_EMPTY_CHAR); /* Store the empty char to the transmit register */
          ErrorMask |= LDD_I2C_SLAVE_TX_UNDERRUN; /* Set the SlaveTxUnderrun error mask */
          DeviceDataPrv->Stats.SlaveTxUnderrun++; /* Increment SlaveTxUnderrun counter */
        }
      } else {
        I2C2_OnSlaveRxRequest(DeviceDataPrv->UserData); /* Invoke OnSlaveRxRequest event */
        I2C_PDD_SetTransmitMode(I2C0_BASE_PTR, I2C_PDD_RX_DIRECTION); /* Switch to Rx mode */
        (void)I2C_PDD_ReadDataReg(I2C0_BASE_PTR); /* Dummy read character */
      }
    } else {
      if ((Status & I2C_PDD_ARBIT_LOST) != 0x00U) { /* Arbitration lost? */
        ErrorMask |= LDD_I2C_ARBIT_LOST; /* Set the ArbitLost error mask */
        DeviceDataPrv->Stats.ArbitLost++; /* Increment ArbitLost counter */
      } else {
        if (I2C_PDD_GetTransmitMode(I2C0_BASE_PTR) == I2C_PDD_TX_DIRECTION) { /* Transmit? */
          if ((Status & I2C_PDD_RX_ACKNOWLEDGE) != 0x00U) { /* NACK from receiver */
            I2C_PDD_SetTransmitMode(I2C0_BASE_PTR, I2C_PDD_RX_DIRECTION); /* Switch to Rx mode */
            (void)I2C_PDD_ReadDataReg(I2C0_BASE_PTR); /* Dummy read character */
          } else {
            if (DeviceDataPrv->OutLenS < DeviceDataPrv->OutLenSReq) { /* Is the requested number of characters transmitted? */
              DeviceDataPrv->OutLenS++; /* Decrease number of chars in the transmit buffer */
              I2C_PDD_WriteDataReg(I2C0_BASE_PTR, *(DeviceDataPrv->OutPtrS)++); /* Store char to transmitter register */
              DeviceDataPrv->Stats.SlaveSentChars++; /* Increment SlaveSentChars counter */
              if (DeviceDataPrv->OutLenS == DeviceDataPrv->OutLenSReq) { /* Is last char. transmitted? */
                Flags |= ON_SLAVE_BLOCK_SENT; /* Set OnSlaveBlockSent flag if last character was sent */
                DeviceDataPrv->OutLenSReq = 0x00U; /* Slave block is transmitted */
              }
            } else {
              I2C_PDD_WriteDataReg(I2C0_BASE_PTR, I2C2_EMPTY_CHAR); /* Store the empty char to the transmit register */
              ErrorMask |= LDD_I2C_SLAVE_TX_UNDERRUN; /* Set the SlaveTxUnderrun error mask */
              DeviceDataPrv->Stats.SlaveTxUnderrun++; /* Increment SlaveTxUnderrun counter */
            }
          }
        } else {
          if (DeviceDataPrv->InpLenS < DeviceDataPrv->InpLenSReq) { /* Is the requested number of characters received? */
            DeviceDataPrv->InpLenS++;  /* Increment number of chars in the receive buffer */
            *(DeviceDataPrv->InpPtrS)++ = I2C_PDD_ReadDataReg(I2C0_BASE_PTR); /* Save received char to the receive buffer */
            I2C2_OnSlaveByteReceived(DeviceDataPrv->UserData); /* Invoke OnSlaveByteReceived event */
            DeviceDataPrv->Stats.SlaveReceivedChars++; /* Increment SlaveReceivedChars counter */
            if (DeviceDataPrv->InpLenS == DeviceDataPrv->InpLenSReq) { /* Is number of bytes in the receive buffer equal to the size of buffer? */
              Flags |= ON_SLAVE_BLOCK_RECEIVED; /* Set OnSlaveBlockReceived flag */
              DeviceDataPrv->InpLenSReq = 0x00U; /* Slave block is received */
            }
          } else {
            (void)I2C_PDD_ReadDataReg(I2C0_BASE_PTR); /* Dummy read data register */
            ErrorMask |= LDD_I2C_SLAVE_RX_OVERRUN; /* Set the SlaveRxOverrun error mask */
            DeviceDataPrv->Stats.SlaveRxOverrun++; /* Increment SlaveRxOverrun counter */
          }
        }
      }
    }
    if ((Flags & ON_SLAVE_BLOCK_SENT) != 0x00U) { /* Is OnSlaveBlockSent flag set? */
      DeviceDataPrv->StatusFlag |= SLAVE_BLOCK_SENT; /* Set data block sent flag */
      I2C2_OnSlaveBlockSent(DeviceDataPrv->UserData); /* If yes then invoke user event */
    }
    if ((Flags & ON_SLAVE_BLOCK_RECEIVED) != 0x00U) { /* Is OnSlaveBlockReceived flag set? */
      DeviceDataPrv->StatusFlag |= SLAVE_BLOCK_RECEIVED; /* Set data block received flag */
      I2C2_OnSlaveBlockReceived(DeviceDataPrv->UserData); /* If yes then invoke user event */
    }
    if (ErrorMask != 0x00U) {          /* Is any error mask set? */
      DeviceDataPrv->ErrorMask |= ErrorMask; /* Update list of error mask value */
      I2C2_OnError(DeviceDataPrv->UserData); /* If yes then invoke user event */
    }
  }
}

/*
** ===================================================================
**     Method      :  I2C2_Init (component I2C_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc.
**         If the "Enable in init. code" is set to "yes" value then the
**         device is also enabled(see the description of the Enable()
**         method). In this case the Enable() method is not necessary
**         and needn't to be generated. 
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the device data structure. 
*/
/* ===================================================================*/
LDD_TDeviceData* I2C2_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate HAL device structure */
  I2C2_TDeviceData *DeviceDataPrv;
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;

  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */

  /* Clear the statistics structure */
  DeviceDataPrv->Stats.MasterSentChars = 0x00U;
  DeviceDataPrv->Stats.MasterReceivedChars = 0x00U;
  DeviceDataPrv->Stats.MasterNacks = 0x00U;
  DeviceDataPrv->Stats.ArbitLost = 0x00U;
  DeviceDataPrv->Stats.SlaveSentChars = 0x00U;
  DeviceDataPrv->Stats.SlaveReceivedChars = 0x00U;
  DeviceDataPrv->Stats.SlaveTxUnderrun = 0x00U;
  DeviceDataPrv->Stats.SlaveRxOverrun = 0x00U;
  DeviceDataPrv->Stats.SlaveGeneralCallAddr = 0x00U;
  DeviceDataPrv->Stats.SlaveSmBusCallAddr = 0x00U;
  DeviceDataPrv->Stats.SlaveSmBusAlertResponse = 0x00U;
  DeviceDataPrv->Stats.SCLLowTimeout = 0x00U;
  DeviceDataPrv->Stats.SDALowTimeout = 0x00U;

  /* Allocate interrupt vector */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_I2C0__DEFAULT_RTOS_ISRPARAM = DeviceDataPrv;
  DeviceDataPrv->SerFlag = 0x00U;      /* Reset all flags */
  DeviceDataPrv->InpLenSReq = 0x00U;   /* No char in the receive buffer */
  DeviceDataPrv->InpLenS = 0x00U;      /* Set zero counter of data of reception */
  DeviceDataPrv->OutLenSReq = 0x00U;   /* No char in the transmit buffer */
  DeviceDataPrv->OutLenS = 0x00U;      /* Set zero counter of data of transmission */
  DeviceDataPrv->StatusFlag = 0x00U;   /* Clear data block transfer complete flags */
  DeviceDataPrv->ErrorMask = 0x00U;    /* Clear variable for errors mask value */
  /* SIM_SCGC4: I2C0=1 */
  SIM_SCGC4 |= SIM_SCGC4_I2C0_MASK;
  /* I2C0_C1: IICEN=0,IICIE=0,MST=0,TX=0,TXAK=0,RSTA=0,WUEN=0,??=0 */
  I2C0_C1 = 0x00U;                     /* Clear control register */
  /* I2C0_FLT: SHEN=0,STOPF=1,SSIE=0,STARTF=1,FLT=0 */
  I2C0_FLT = (I2C_FLT_STOPF_MASK | I2C_FLT_STARTF_MASK | I2C_FLT_FLT(0x00)); /* Clear bus status interrupt flags */
  /* I2C0_S: TCF=0,IAAS=0,BUSY=0,ARBL=0,RAM=0,SRW=0,IICIF=1,RXAK=0 */
  I2C0_S = I2C_S_IICIF_MASK;           /* Clear interrupt flag */
  /* PORTB_PCR4: ISF=0,MUX=2 */
  PORTB_PCR4 = (uint32_t)((PORTB_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* PORTB_PCR3: ISF=0,MUX=2 */
  PORTB_PCR3 = (uint32_t)((PORTB_PCR3 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* NVIC_IPR2: PRI_8=0x40 */
  NVIC_IPR2 = (uint32_t)((NVIC_IPR2 & (uint32_t)~(uint32_t)(
               NVIC_IP_PRI_8(0xBF)
              )) | (uint32_t)(
               NVIC_IP_PRI_8(0x40)
              ));
  /* NVIC_ISER: SETENA|=0x0100 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x0100);
  /* I2C0_A1: AD=0x2A,??=0 */
  I2C0_A1 = I2C_A1_AD(0x2A);           /* Define slave address */
  /* I2C0_C2: GCAEN=0,ADEXT=0,HDRS=0,SBRC=0,RMEN=0,AD=0 */
  I2C0_C2 = I2C_C2_AD(0x00);
  /* I2C0_FLT: SHEN=0,STOPF=0,SSIE=0,STARTF=0,FLT=5 */
  I2C0_FLT = I2C_FLT_FLT(0x05);        /* Set glitch filter register */
  /* I2C0_F: MULT=0,ICR=0x22 */
  I2C0_F = (I2C_F_MULT(0x00) | I2C_F_ICR(0x22)); /* Set prescaler bits */
  I2C_PDD_EnableDevice(I2C0_BASE_PTR, PDD_ENABLE); /* Enable device */
  I2C_PDD_EnableInterrupt(I2C0_BASE_PTR); /* Enable interrupt */
  I2C_PDD_EnableWakeUp(I2C0_BASE_PTR, PDD_ENABLE); /* Enable wakeup */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_I2C2_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv); /* Return pointer to the data data structure */
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveSendBlock (component I2C_LDD)
*/
/*!
**     @brief
**         This method writes a block of characters to the I2C bus
**         after the master starts the communication. If no character
**         is ready for a transmission (user's output slave buffer is
**         empty or method SlaveSendBlock is not call), the "Empty
**         character" will be sent (see "Empty character" property). In
**         SLAVE mode the data are not copied to an internal buffer and
**         remains in the original location. Therefore the content of
**         the buffer should not be changed until the transmission is
**         complete. If the method returns ERR_OK, it doesn't mean that
**         transmission was successful. The state of transmission is
**         detectable by means of events (OnSlaveBlockSent or OnError).
**         This method is available only for the SLAVE or MASTER -
**         SLAVE mode.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         BufferPtr       - Pointer to the block of data
**                           to send.
**     @param
**         Size            - Size of the data block.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_BUSY - The I2C device is busy
*/
/* ===================================================================*/
LDD_TError I2C2_SlaveSendBlock(LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, LDD_I2C_TSize Size)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  if (Size == 0x00U) {                 /* Test variable Size on zero */
    return ERR_OK;                     /* If zero then OK */
  }
  if (DeviceDataPrv->OutLenSReq != 0x00U) { /* Is the bus busy */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  DeviceDataPrv->OutPtrS = (uint8_t *)BufferPtr; /* Save pointer to data for transmitting */
  DeviceDataPrv->OutLenSReq = Size;    /* Set length of data */
  DeviceDataPrv->OutLenS = 0x00U;      /* Set number of sent characters to zero. */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveGetBlockSentStatus (component I2C_LDD)
*/
/*!
**     @brief
**         This method returns current state of SlaveSendBlock method.
**         This method is available only for the SLAVE mode and if
**         method SlaveSendBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Return value:
**                           <true> - data block is completely
**                           transmitted.
**                           <false> - data block isn't completely
**                           transmitted.
*/
/* ===================================================================*/
bool I2C2_SlaveGetBlockSentStatus(LDD_TDeviceData *DeviceDataPtr)
{
  uint8_t Status;                      /* Temporary variable for flag saving */

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  Status = ((I2C2_TDeviceDataPtr)DeviceDataPtr)->StatusFlag; /* Save flag for return */
  ((I2C2_TDeviceDataPtr)DeviceDataPtr)->StatusFlag &= (uint8_t)(~(uint8_t)SLAVE_BLOCK_SENT); /* Clear data block sent flag */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return (bool)(((Status & SLAVE_BLOCK_SENT) != 0x00U)? TRUE : FALSE); /* Return saved status */
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveGetSentDataNum (component I2C_LDD)
*/
/*!
**     @brief
**         This method returns the number of transmitted characters
**         from the transmit buffer. This method is available only for
**         the SLAVE mode and if method SlaveSendBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - The number of sent characters.
*/
/* ===================================================================*/
LDD_I2C_TSize I2C2_SlaveGetSentDataNum(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  return (DeviceDataPrv->OutLenS);
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveCancelTransmissionBlock (component I2C_LDD)
*/
/*!
**     @brief
**         This method cancels transmission of SlaveSendBlock method.
**         This method is available only for the SLAVE mode and if
**         method SlaveSendBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED - Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError I2C2_SlaveCancelTransmissionBlock(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  DeviceDataPrv->OutLenSReq = 0x00U;   /*Set zero length of data for transmission */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}
/*
** ===================================================================
**     Method      :  I2C2_SlaveReceiveBlock (component I2C_LDD)
*/
/*!
**     @brief
**         This method receives a block of characters of the I2C bus
**         after the master starts the communication. In SLAVE mode the
**         data are not copied to an internal buffer and remains in the
**         original location. Therefore the content of the buffer
**         should not be changed until the transmission is complete. If
**         the method returns ERR_OK, it doesn't mean that transmission
**         was successful. The state of transmission is detectable by
**         means of events (OnSlaveBlockReceived or OnError). State
**         LDD_I2C_SLAVE_TX_UNDERRUN of method GetError is return, when
**         no character is ready for a reception  (user's input slave
**         buffer is empty). This method is available only for the
**         SLAVE or MASTER - SLAVE mode.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         BufferPtr       - Pointer to A buffer where
**                           received characters will be stored.
**     @param
**         Size            - The size of the block.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_BUSY - The I2C device is busy
*/
/* ===================================================================*/
LDD_TError I2C2_SlaveReceiveBlock(LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, LDD_I2C_TSize Size)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  if (Size == 0x00U) {                 /* Test variable Size on zero */
    return ERR_OK;                     /* If zero then OK */
  }
  if (DeviceDataPrv->InpLenSReq != 0x00U) { /* Is the bus busy */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  DeviceDataPrv->InpPtrS = (uint8_t *)BufferPtr; /* Save pointer to data for transmitting */
  DeviceDataPrv->InpLenSReq = Size;    /* Set length of data */
  DeviceDataPrv->InpLenS = 0x00U;      /* Set number of received characters to zero. */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveGetBlockReceivedStatus (component I2C_LDD)
*/
/*!
**     @brief
**         This method returns current state of SlaveReceiveBlock
**         method. This method is available only for the SLAVE mode and
**         if method SlaveReceiveBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Return value:
**                           <true> - data block is completely received.
**                           <false> - data block isn't completely
**                           received.
*/
/* ===================================================================*/
bool I2C2_SlaveGetBlockReceivedStatus(LDD_TDeviceData *DeviceDataPtr)
{
  uint8_t Status;                      /* Temporary variable for flag saving */

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  Status = ((I2C2_TDeviceDataPtr)DeviceDataPtr)->StatusFlag; /* Save flag for return */
  ((I2C2_TDeviceDataPtr)DeviceDataPtr)->StatusFlag &= (uint8_t)(~(uint8_t)SLAVE_BLOCK_RECEIVED); /* Clear data block received flag */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return (bool)(((Status & SLAVE_BLOCK_RECEIVED) != 0x00U)? TRUE : FALSE); /* Return saved status */
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveGetReceivedDataNum (component I2C_LDD)
*/
/*!
**     @brief
**         This method returns the number of received characters in the
**         receive buffer. This method is available only for the SLAVE
**         mode and if method SlaveReceiveBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - The number of characters in the input
**                           buffer.
*/
/* ===================================================================*/
LDD_I2C_TSize I2C2_SlaveGetReceivedDataNum(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  return (DeviceDataPrv->InpLenS);
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveUpdateReceiveBlockSize (component I2C_LDD)
*/
/*!
**     @brief
**         This method updates received block size in slave mode. For
**         correct function must this method called in
**         OnSlaveByteReceived. This method is available only for the
**         Slave or MASTER - SLAVE mode.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Size            - The size of the block.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_NOTAVAIL - It is not possible set new
**                           value receive block size, slave is not
**                           receive block.
**                           ERR_PARAM_SIZE -  Value of block size is
**                           out of range.
*/
/* ===================================================================*/
LDD_TError I2C2_SlaveUpdateReceiveBlockSize(LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TSize Size)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  if (DeviceDataPrv->InpLenS == 0U) {  /* Is the Slave receive data? */
    return ERR_NOTAVAIL;               /* If no, return error */
  }
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  if (Size < DeviceDataPrv->InpLenS) { /* Is new size less than old size? */
    /* {Default RTOS Adapter} Critical section end, general PE function is used */
    ExitCritical();
    return ERR_PARAM_SIZE;             /* If yes, return error */
  }
  DeviceDataPrv->InpLenSReq = Size;
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_SlaveCancelReceptionBlock (component I2C_LDD)
*/
/*!
**     @brief
**         This method cancels reception of SlaveReceiveBlock method.
**         This method is available only for the SLAVE mode and if
**         method SlaveReceiveBlock is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED - Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError I2C2_SlaveCancelReceptionBlock(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  DeviceDataPrv->InpLenSReq = 0x00U;   /* Set zero length of data for reception */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_GetError (component I2C_LDD)
*/
/*!
**     @brief
**         Returns value of error mask, e.g. LDD_I2C_ARBIT_LOST.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         ErrorMaskPtr    - Pointer to a variable
**                           where errors value mask will be stored.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError I2C2_GetError(LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TErrorMask *ErrorMaskPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  *ErrorMaskPtr = DeviceDataPrv->ErrorMask; /* Return last value of error mask */
  DeviceDataPrv->ErrorMask = 0x00U;
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_CheckBus (component I2C_LDD)
*/
/*!
**     @brief
**         This method returns the status of the bus. If the START
**         condition has been detected, the method returns LDD_I2C_BUSY.
**         If the STOP condition has been detected, the method returns
**         LDD_I2C_IDLE.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         BusStatePtr     - Pointer to a variable,
**                           where value of status is stored.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError I2C2_CheckBus(LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TBusState *BusStatePtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  (void)DeviceDataPrv;                 /* Suppress unused variable warning if needed */
  *BusStatePtr = (LDD_I2C_TBusState)((I2C_PDD_GetBusStatus(I2C0_BASE_PTR) == I2C_PDD_BUS_BUSY)?LDD_I2C_BUSY:LDD_I2C_IDLE); /* Return value of Busy bit in status register */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  I2C2_GetStats (component I2C_LDD)
*/
/*!
**     @brief
**         Returns receive/transmit statistics.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Device receive/transmit statistics since the
**                           device initialization or since the
**                           statistical information has been cleared.
*/
/* ===================================================================*/
LDD_I2C_TStats I2C2_GetStats(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  return (DeviceDataPrv->Stats);
}

/*
** ===================================================================
**     Method      :  I2C2_ClearStats (component I2C_LDD)
*/
/*!
**     @brief
**         Clears the receive/transmit statistics. This method is
**         available only when GetStats methos is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void I2C2_ClearStats(LDD_TDeviceData *DeviceDataPtr)
{
  I2C2_TDeviceData *DeviceDataPrv = (I2C2_TDeviceData *)DeviceDataPtr;

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  /* Clear the statistics structure */
  DeviceDataPrv->Stats.MasterSentChars = 0x00U;
  DeviceDataPrv->Stats.MasterReceivedChars = 0x00U;
  DeviceDataPrv->Stats.MasterNacks = 0x00U;
  DeviceDataPrv->Stats.ArbitLost = 0x00U;
  DeviceDataPrv->Stats.SlaveSentChars = 0x00U;
  DeviceDataPrv->Stats.SlaveReceivedChars = 0x00U;
  DeviceDataPrv->Stats.SlaveTxUnderrun = 0x00U;
  DeviceDataPrv->Stats.SlaveRxOverrun = 0x00U;
  DeviceDataPrv->Stats.SlaveGeneralCallAddr = 0x00U;
  DeviceDataPrv->Stats.SlaveSmBusCallAddr = 0x00U;
  DeviceDataPrv->Stats.SlaveSmBusAlertResponse = 0x00U;
  DeviceDataPrv->Stats.SCLLowTimeout = 0x00U;
  DeviceDataPrv->Stats.SDALowTimeout = 0x00U;
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
}

/* END I2C2. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
